baseURL = "https://yngraphics.github.io/"
title = "YN Graphics"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "YN Graphics" # title for frontpage, may include image
copyright = "YN Graphics"
description = 'brochure | poster | menu card | banners | facebook post | branding package<br />label | logo | business card | product package | Invitation Card | Wedding Cards | Leaflet | Certificate<br />Photocopy | Laminating | Binding | Mug Printing | Art Work Design & Etc'
startbuttonText = "Contact"
startbuttonLink = "#contact"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

# [[params.menu.main]]
# url = '/'
# title = "Home"

# [[params.menu.main]]
# url = '/posts/'
# title = "Posts"

# [taxonomies]
#     tag = "tags"
#     category = "categories"
#     series = "series"

[params.one]
enable = true
title = 'Creating Stunning Graphics for Lasting Impressions'
body = '''
Welcome to YN Graphics, your go-to destination for all your design needs. We offer a wide range of services, including brochure and poster design, menu card creation, banner design, Facebook post graphics, branding packages, label and logo design, business card and product packaging design, invitation and wedding card customization, leaflet creation, professional certificates, photocopying, laminating, binding, mug printing, and art work design. Our dedicated team of designers is committed to delivering exceptional results, capturing your vision and transforming it into captivating visuals. Experience the power of outstanding design with YN Graphics, where creativity meets excellence.
'''

# [[params.one.icon]]
# icon = "fa-gem"
# style = "1"
# label = "Lorem"

# [[params.one.icon]]
# icon = "fa-heart"
# style = "2"
# label = "Ipsum"

# [[params.one.icon]]
# icon = "solid fa-code"
# style = "3"
# label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Artworks Design'
body = 'At YN Graphics, we excel in artwork design, providing innovative and visually captivating solutions that bring your creative visions to life.'

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Business  Cards'
body = 'Elevate your professional image with YN Graphics meticulously crafted business cards, designed to make a lasting impression and leave a memorable mark on potential clients and contacts.'

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Invitation Cards'
body = 'Make every special occasion unforgettable with YN Graphics exquisite invitation cards, meticulously designed to reflect your unique style and set the perfect tone for your event.'

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Wedding Cards'
body = 'Celebrate the joy of love and create cherished memories with YN Graphics exquisite wedding cards, where elegance and sophistication meet heartfelt design to set the perfect tone for your special day.'

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Wedding Cards'
body = 'Celebrate the joy of love and create cherished memories with YN Graphics exquisite wedding cards, where elegance and sophistication meet heartfelt design to set the perfect tone for your special day.'

[params.three]
enable = false
title = 'Accumsan mus tortor nunc aliquet'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-code"
title = "Foo bar"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-headphones-alt"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag"
title = "Nothing important"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = false
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = false
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
