baseURL = "https://yngraphics.github.io/"
title = "YN Graphics"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "YN Graphics" # title for frontpage, may include image
copyright = "YN Graphics"
description = 'brochure | poster | menu card | banners | facebook post<br />branding package label | logo | business card | product package | Invitation Card<br />Wedding Cards | Leaflet | Certificate | Photocopy | Laminating | Binding<br />Mug Printing | Art Work Design & Etc'
startbuttonText = "Contact"
startbuttonLink = "#contact"
body_is_markdown = true
# custom_css = "custom.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

# [[params.menu.main]]
# url = '/'
# title = "Home"

# [[params.menu.main]]
# url = '/posts/'
# title = "Posts"

# [taxonomies]
#     tag = "tags"
#     category = "categories"
#     series = "series"

[params.one]
enable = true
title = 'Creating Stunning Graphics for Lasting Impressions'
body = '''
Welcome to YN Graphics, your go-to destination for all your design needs. We offer a wide range of services, including brochure and poster design, menu card creation, banner design, Facebook post graphics, branding packages, label and logo design, business card and product packaging design, invitation and wedding card customization, leaflet creation, professional certificates, photocopying, laminating, binding, mug printing, and art work design. Our dedicated team of designers is committed to delivering exceptional results, capturing your vision and transforming it into captivating visuals. Experience the power of outstanding design with YN Graphics, where creativity meets excellence.
'''

# [[params.one.icon]]
# icon = "fa-gem"
# style = "1"
# label = "Lorem"

# [[params.one.icon]]
# icon = "fa-heart"
# style = "2"
# label = "Ipsum"

# [[params.one.icon]]
# icon = "solid fa-code"
# style = "3"
# label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "img/1.jpg"
title = 'Logo Design'
body = "Unlock the essence of your brand with YN Graphics' expertly crafted logo designs, capturing its identity and leaving a memorable mark in the minds of your target audience."

[[params.two.section]]
img = "img/2.jpg"
title = 'Artworks Design'
body = 'At YN Graphics, we excel in artwork design, providing innovative and visually captivating solutions that bring your creative visions to life.'

[[params.two.section]]
img = "img/3.jpg"
title = 'Business  Cards'
body = 'Elevate your professional image with YN Graphics meticulously crafted business cards, designed to make a lasting impression and leave a memorable mark on potential clients and contacts.'

[[params.two.section]]
img = "img/4.jpg"
title = 'Invitation Cards'
body = 'Make every special occasion unforgettable with YN Graphics exquisite invitation cards, meticulously designed to reflect your unique style and set the perfect tone for your event.'

[[params.two.section]]
img = "img/5.jpg"
title = 'Wedding Cards'
body = 'Celebrate the joy of love and create cherished memories with YN Graphics exquisite wedding cards, where elegance and sophistication meet heartfelt design to set the perfect tone for your special day.'

[[params.two.section]]
img = "img/6.jpg"
title = 'Leaflet'
body = 'Ignite curiosity and inspire action with YN Graphics captivating leaflets, designed to grab attention and deliver your message succinctly and persuasively.'

[[params.two.section]]
img = "img/7.jpg"
title = 'Certificate'
body = 'Celebrate achievements and recognize excellence with YN Graphics meticulously designed certificates, reflecting prestige and honor while capturing the essence of accomplishment.'

[[params.two.section]]
img = "img/8.jpg"
title = 'Brochure'
body = "Captivating designs that showcase your brand's offerings and leave a lasting impression."

[[params.two.section]]
img = "img/9.jpg"
title = 'Poster'
body = "Make a bold statement with YN Graphics' striking posters, designed to captivate viewers and leave a lasting impression with their impactful visuals."

[[params.two.section]]
img = "img/10.jpg"
title = 'Menu Cards'
body = "Delight your customers with YN Graphics' enticing menu cards, showcasing delectable offerings in an aesthetically pleasing and informative manner."

[[params.two.section]]
img = "img/11.jpg"
title = 'Banners'
body = "Command attention and create a powerful visual presence with YN Graphics' impactful banners, designed to leave a lasting impression and effectively promote your brand or event."

[[params.two.section]]
img = "img/12.jpg"
title = 'Social Media Posts'
body = "Drive engagement and build a strong online presence with YN Graphics' captivating social media posts, designed to spark interest, increase reach, and leave a lasting impact on your audience."

[[params.two.section]]
img = "img/13.jpg"
title = 'Product Package & Label'
body = "Enhance your product's appeal and communicate its unique qualities with YN Graphics' meticulously designed packaging and labels, combining captivating visuals and informative elements to stand out on the shelves."

[params.three]
enable = false
title = 'Accumsan mus tortor nunc aliquet'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = true
title = "Yashod Nawarathna"
body = "Introducing Mr. Yashod Nawarathna, the creative force behind YN Graphics. With a passion for design and an eye for detail, YN Graphics brings a unique blend of artistry and expertise to every project. Their exceptional talent and deep understanding of visual communication allow them to create captivating designs that leave a lasting impression. Trust YN Graphics to bring your vision to life with their creative genius and unwavering commitment to excellence."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+94 (0) 714 320 842"
address = "No 99/3<br />Badulla Road<br />Bindunuwewa<br />Bandarawela"
email = "yngraphics23@gmail.com"
subject = "YN Graphics"
formspree_form_id = "xbjvrgyk"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

# [languages.de]
# weight = 10
# languageName = "Deutsch"
